#!/bin/bash

echo "========================================="
echo "📚 RECOMMENDED ADDITIONS TO IRONCLAD STACK"
echo "========================================="
echo ""

echo "🍜 ASIAN NOODLE & RICE DISHES"
echo "========================================="
echo "1. Pad Thai - Thailand's national dish"
echo "   Why: Perfect balance of sweet, sour, salty, spicy"
echo "   Search: 'Pad Thai authentic recipe'"
echo ""
echo "2. Bibimbap - Korean mixed rice bowl"
echo "   Why: Beautiful presentation, healthy, customizable"
echo "   Search: 'Bibimbap Korean recipe'"
echo ""
echo "3. Pho - Vietnamese noodle soup"
echo "   Why: Complex broth, aromatic spices, comfort in a bowl"
echo "   Search: 'Pho noodle soup recipe'"
echo ""

echo "🥘 INDIAN CURRIES"
echo "========================================="
echo "4. Butter Chicken (Murgh Makhani)"
echo "   Why: Creamy, rich, most popular Indian dish worldwide"
echo "   Search: 'Butter chicken recipe'"
echo ""
echo "5. Lamb Rogan Josh - Kashmiri curry"
echo "   Why: Aromatic, deep red color, tender lamb"
echo "   Search: 'Rogan josh lamb curry'"
echo ""

echo "🌮 MEXICAN & LATIN AMERICAN"
echo "========================================="
echo "6. Birria Tacos - Mexican shredded beef tacos"
echo "   Why: Viral sensation, consommé for dipping"
echo "   Search: 'Birria tacos recipe'"
echo ""
echo "7. Ceviche - Peruvian raw fish dish"
echo "   Why: Fresh, citrusy, perfect for summer"
echo "   Search: 'Peruvian ceviche recipe'"
echo ""

echo "🍰 DESSERTS & BAKED GOODS"
echo "========================================="
echo "8. Crème Brûlée - French custard dessert"
echo "   Why: Elegant, satisfying crack of caramelized sugar"
echo "   Search: 'Creme brulee recipe'"
echo ""
echo "9. Tiramisu - Italian coffee dessert"
echo "   Why: No-bake, coffee-soaked ladyfingers"
echo "   Search: 'Tiramisu authentic recipe'"
echo ""

echo "🥩 GRILL & BBQ"
echo "========================================="
echo "10. Tomahawk Steak - Reverse sear method"
echo "    Why: Impressive presentation, perfect for special occasions"
echo "    Search: 'Reverse sear tomahawk steak'"
echo ""

echo "========================================="
echo "🔧 QUICK ADDITION COMMANDS"
echo "========================================="
echo "To add any recipe to Mealie manually:"
echo "1. Open Mealie: http://10.10.10.9:9925"
echo "2. Click 'Create Recipe'"
echo "3. Copy from source"
echo "4. Add to your collection"
echo "========================================="
